"use client"

import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import {
  AlertTriangle,
  Scale,
  Globe,
  Shield,
  CheckCircle,
  XCircle,
  ExternalLink,
  Users,
  FileText,
  Gavel,
  Info
} from "lucide-react"

interface DisclaimerProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  uiStyle?: "modern" | "pixel"
}

export function Disclaimer({ open, onOpenChange, uiStyle = "modern" }: DisclaimerProps) {
  const disclaimerSections = [
    {
      icon: AlertTriangle,
      title: "AI-Generated Content Limitations",
      items: [
        "All responses are generated by third-party AI models (Groq, Gemini, OpenAI, Claude)",
        "AI responses may contain inaccuracies, incomplete information, or biased content",
        "Always verify AI-generated information before making important decisions",
        "Content may not reflect current events or real-time data",
        "AI models can produce hallucinations or fabricated information"
      ]
    },
    {
      icon: Users,
      title: "User Responsibility",
      items: [
        "You are solely responsible for the questions, queries, and prompts you submit",
        "Ensure your use complies with applicable laws and regulations in your jurisdiction",
        "Do not share sensitive, confidential, or personal information",
        "Use the platform ethically and responsibly",
        "Respect intellectual property rights and privacy of others"
      ]
    },
    {
      icon: Scale,
      title: "Legal & Compliance",
      items: [
        "Different countries have varying legal obligations regarding AI usage",
        "Users must comply with local, national, and international laws",
        "Follow your government's guidelines on AI technology usage",
        "Consult legal professionals for jurisdiction-specific compliance",
        "Mackdev Inc. is not liable for violations of local regulations"
      ]
    },
    {
      icon: XCircle,
      title: "Prohibited Uses",
      items: [
        "Do not use for illegal, harmful, or malicious activities",
        "Prohibited: harassment, discrimination, hate speech, or violence",
        "No generation of misleading, defamatory, or false content",
        "Avoid creating content that violates intellectual property rights",
        "Do not attempt to manipulate, hack, or abuse the system"
      ]
    },
    {
      icon: Shield,
      title: "Third-Party AI Ownership & Management",
      items: [
        "We do not claim any ownership rights or legal rights over third-party AI tools and models",
        "All AI models are exclusively managed, developed, owned, and trained by their respective vendors",
        "Third-party AI providers may change, update, or discontinue their services without prior notification",
        "We hold no control, obligation, or liability over the performance of third-party AI models",
        "Each AI provider operates under their own terms of service and privacy policies",
        "Users acknowledge that AI model availability and functionality are subject to vendor discretion"
      ]
    }
  ]

  const providers = [
    { name: "Groq", description: "Lightning-fast AI inference engine" },
    { name: "Gemini", description: "Google's advanced multimodal AI" },
    { name: "OpenAI", description: "Creator of GPT and ChatGPT models" },
    { name: "Claude", description: "Anthropic's constitutional AI assistant" }
  ]

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className={`max-w-4xl max-h-[90vh] overflow-y-auto ${
        uiStyle === "pixel"
          ? "bg-gray-200 dark:bg-gray-800 border-4 border-gray-400 dark:border-gray-600 pixel-border rounded-none"
          : "bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg"
      }`}>
        <DialogHeader className="space-y-4">
          <div className="flex items-center justify-center space-x-3">
            <div className={`p-3 bg-gradient-to-br from-orange-500 to-red-600 ${
              uiStyle === "pixel" ? "pixel-border border-4 border-orange-400" : "rounded-lg"
            }`}>
              <FileText className="w-8 h-8 text-white" />
            </div>
            <div className="text-center">
              <DialogTitle className={`text-2xl font-bold text-gray-900 dark:text-gray-100 ${
                uiStyle === "pixel" ? "pixel-font" : ""
              }`}>
                {uiStyle === "pixel" ? "DISCLAIMER & TERMS" : "Disclaimer & Terms of Use"}
              </DialogTitle>
              <p className={`text-sm text-gray-600 dark:text-gray-400 ${
                uiStyle === "pixel" ? "pixel-font" : ""
              }`}>
                Important information about using ONE.AI
              </p>
            </div>
          </div>
          
          <div className="flex items-center justify-center">
            <Badge variant="outline" className={`text-orange-600 border-orange-300 ${
              uiStyle === "pixel" ? "pixel-font border-2" : ""
            }`}>
              Please read carefully before using the platform
            </Badge>
          </div>
        </DialogHeader>

        <div className="space-y-6 pt-4">
          {/* General Warning */}
          <Card className={`border-orange-200 dark:border-orange-800 ${
            uiStyle === "pixel" ? "border-2" : ""
          }`}>
            <CardHeader>
              <CardTitle className={`flex items-center gap-2 text-orange-700 dark:text-orange-400 ${
                uiStyle === "pixel" ? "pixel-font" : ""
              }`}>
                <AlertTriangle className="h-5 w-5" />
                {uiStyle === "pixel" ? "IMPORTANT NOTICE" : "Important Notice"}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className={`text-gray-700 dark:text-gray-300 leading-relaxed ${
                uiStyle === "pixel" ? "pixel-font text-xs" : ""
              }`}>
                ONE.AI is an AI-powered platform that provides responses generated by third-party artificial intelligence models. 
                By using this service, you acknowledge and agree to the terms, limitations, and responsibilities outlined below. 
                This platform is provided "as-is" without warranties of any kind.
              </p>
            </CardContent>
          </Card>

          {/* Disclaimer Sections */}
          {disclaimerSections.map((section, index) => {
            const Icon = section.icon
            return (
              <Card key={index} className={uiStyle === "pixel" ? "border-2" : ""}>
                <CardHeader>
                  <CardTitle className={`flex items-center gap-2 ${
                    uiStyle === "pixel" ? "pixel-font" : ""
                  }`}>
                    <Icon className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                    {section.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {section.items.map((item, itemIndex) => (
                      <li key={itemIndex} className={`flex items-start space-x-2 text-sm text-gray-700 dark:text-gray-300 ${
                        uiStyle === "pixel" ? "pixel-font text-xs" : ""
                      }`}>
                        <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            )
          })}

          <Separator />

          {/* AI Providers */}
          <div>
            <h3 className={`text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4 text-center ${
              uiStyle === "pixel" ? "pixel-font" : ""
            }`}>
              {uiStyle === "pixel" ? "THIRD-PARTY AI PROVIDERS" : "Third-Party AI Providers"}
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {providers.map((provider, index) => (
                <div key={index} className={`flex items-center space-x-3 p-3 ${
                  uiStyle === "pixel"
                    ? "bg-gray-100 dark:bg-gray-700 border-2 border-gray-400 dark:border-gray-600"
                    : "bg-gray-50 dark:bg-gray-800/50 rounded-lg"
                }`}>
                  <Shield className="w-5 h-5 text-blue-600 dark:text-blue-400 flex-shrink-0" />
                  <div>
                    <h4 className={`text-sm font-medium text-gray-900 dark:text-gray-100 ${
                      uiStyle === "pixel" ? "pixel-font text-xs" : ""
                    }`}>
                      {provider.name}
                    </h4>
                    <p className={`text-xs text-gray-600 dark:text-gray-400 ${
                      uiStyle === "pixel" ? "pixel-font" : ""
                    }`}>
                      {provider.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
            <p className={`text-xs text-gray-500 dark:text-gray-400 text-center mt-3 ${
              uiStyle === "pixel" ? "pixel-font" : ""
            }`}>
              All AI models are provided by their respective companies and subject to their terms of service
            </p>
          </div>

          <Separator />

          {/* Liability & Limitation */}
          <Card className={`border-red-200 dark:border-red-800 ${
            uiStyle === "pixel" ? "border-2" : ""
          }`}>
            <CardHeader>
              <CardTitle className={`flex items-center gap-2 text-red-700 dark:text-red-400 ${
                uiStyle === "pixel" ? "pixel-font" : ""
              }`}>
                <Gavel className="h-5 w-5" />
                {uiStyle === "pixel" ? "LIABILITY LIMITATION" : "Limitation of Liability"}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className={`text-sm text-gray-700 dark:text-gray-300 ${
                uiStyle === "pixel" ? "pixel-font text-xs" : ""
              }`}>
                <strong>No Warranty:</strong> ONE.AI is provided "as-is" without any express or implied warranties. 
                We do not guarantee the accuracy, completeness, or reliability of AI-generated content.
              </p>
              <p className={`text-sm text-gray-700 dark:text-gray-300 ${
                uiStyle === "pixel" ? "pixel-font text-xs" : ""
              }`}>
                <strong>User Responsibility:</strong> You assume all risks associated with using AI-generated content. 
                Mackdev Inc. shall not be liable for any damages arising from your use of this platform.
              </p>
              <p className={`text-sm text-gray-700 dark:text-gray-300 ${
                uiStyle === "pixel" ? "pixel-font text-xs" : ""
              }`}>
                <strong>Indemnification:</strong> You agree to indemnify and hold harmless Mackdev Inc. from any claims, 
                damages, or losses resulting from your use of the platform or violation of these terms.
              </p>
            </CardContent>
          </Card>

          {/* Contact & Updates */}
          <div className="space-y-4">
            <div className="text-center space-y-3">
              <div className="flex items-center justify-center space-x-4">
                <Button
                  variant="outline"
                  size="sm"
                  disabled
                  className={`opacity-50 cursor-not-allowed ${
                    uiStyle === "pixel" ? "pixel-font border-2" : ""
                  }`}
                >
                  <FileText className="w-4 h-4 mr-2" />
                  {uiStyle === "pixel" ? "LEGAL CONTACT" : "Legal Contact"}
                  <ExternalLink className="w-3 h-3 ml-1" />
                </Button>
                
                <Button
                  variant="outline"
                  size="sm"
                  disabled
                  className={`opacity-50 cursor-not-allowed ${
                    uiStyle === "pixel" ? "pixel-font border-2" : ""
                  }`}
                >
                  <Info className="w-4 h-4 mr-2" />
                  {uiStyle === "pixel" ? "TERMS UPDATE" : "Terms Updates"}
                  <ExternalLink className="w-3 h-3 ml-1" />
                </Button>
              </div>

              <div className="space-y-2">
                <p className={`text-xs text-gray-500 dark:text-gray-400 ${
                  uiStyle === "pixel" ? "pixel-font" : ""
                }`}>
                  These terms may be updated periodically. Continued use constitutes acceptance of any changes.
                </p>
                
                <p className={`text-xs text-gray-500 dark:text-gray-500 ${
                  uiStyle === "pixel" ? "pixel-font" : ""
                }`}>
                  Last Updated: December 27, 2025 | © 2025 Mackdev Inc. All rights reserved.
                </p>
                
                <div className="flex items-center justify-center space-x-1 text-xs text-gray-500">
                  <Globe className="w-3 h-3" />
                  <span className={uiStyle === "pixel" ? "pixel-font" : ""}>
                    Global platform - Local laws apply
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}